### ISSUE TITLE
Inconsistent scala version

### ISSUE THREAD

**Issue by NickCody** [Syncleus/aparapi#157]
aparapi has a scala dependency of 2.13.1 and maven-scala-plugin states 2.12.6. Suggest using a single property definition and reference it everywhere. I have a PR for this if you'd like to see it.

**Comment by NickCody** [comment]
Link to commit: https://github.com/NickCody/aparapi/commit/b8c87f7b852a75173b0a4ab6d32023d4b461d3a7

**Comment by freemo** [comment]
This was already fixed in version 2.0.0 released, thanks though.
