### ISSUE TITLE
Better handling of missing drivers

### ISSUE THREAD

**Issue by CC007** [Syncleus/aparapi#39]
Make it so that it is easy for the user of a java program to know that they don't have their openCL drivers installed (GPU/CPU) and provide easy links to the latest drivers for Intel/AMD/Nvidia

**Comment by CC007** [comment]
The intel drivers can be found here:
https://software.intel.com/en-us/articles/opencl-drivers

**Comment by CC007** [comment]
AMD drivers:
http://support.amd.com/en-us/kb-articles/Pages/OpenCL2-Driver.aspx

**Comment by CC007** [comment]
Nvidia drivers:
http://www.nvidia.com/Download/index.aspx?lang=en-us

**Comment by automenta** [comment]
http://packages.ubuntu.com/search?keywords=opencl&searchon=names&suite=yakkety&section=all

**Comment by freemo** [comment]
@CC007 How exactly do you propose we do this? If we throw an exception it will halt the program, so we want to elegantly fall back to native java still when we can, so exceptions arent an option. What other mechanism could there be to automatically provide links to drivers? If aprapi were a GUI program or end-product I would agree with you. But as a library I'm not sure of any elegant way this could be done.

What did you have in mind?
