### ISSUE TITLE
[BOUNTY $10] what do i do to add popcount support?

### ISSUE THREAD

**Issue by zhuker** [Syncleus/aparapi#47]
where do i start if i wanted to add `popcount` support?
https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/popcount.html

**Comment by freemo** [comment]
@zhuker Check out this class, this is where the commands usable in the kernel are defined and mapped to their java equivalent.

https://github.com/Syncleus/aparapi/blob/master/src/main/java/com/aparapi/Kernel.java

**Comment by freemo** [comment]
@zhuker have you made any progress on this? If not I can add a small bounty to try to encourage to get this implemented.
