### ISSUE TITLE
KernelManagers provided KernelManager result in NPE

### ISSUE THREAD

**Issue by seeker** [Syncleus/aparapi#55]
When trying to use `KernelManagers.JTP_ONLY` or `KernelManagers.SEQUENTIAL_ONLY`, the code will fail with a `java.lang.NullPointerException`.

```java
KernelManager.setKernelManager(KernelManagers.JTP_ONLY);
```

**Comment by freemo** [comment]
@seeker not sure if you caught this but I applied your fixes back when you first reported the issue.

**Comment by seeker** [comment]
I saw that. Thanks again for the fast response.
