### ISSUE TITLE
[Bounty $25] Using tanh and NPE in ClassModel

### ISSUE THREAD

**Issue by freemo** [Syncleus/aparapi#6]
_From @stoerr on October 8, 2015 17:37_

I was trying to use tanh by declaring

```
@OpenCLMapping(mapTo = "tanh")
protected float tanh(float _f) {
    return (float) Math.tanh(_f);
}
```

Unfortunately, this exposes a NullPointerException:

java.lang.NullPointerException
    at com.amd.aparapi.internal.model.ClassModel.parse(ClassModel.java:2542)
    at com.amd.aparapi.internal.model.ClassModel.parse(ClassModel.java:2526)
    at com.amd.aparapi.internal.model.ClassModel.<init>(ClassModel.java:142)

The problem is, that it tries to parse java.lang.Math, and Math.class.getClassLoader() returns null, so the ClassModel can't find the class file. I'm not quite sure how aparapi should deal with this - perhaps classes used in methods annotated with @OpenCLMapping shouldn't be parsed at all.

It would be nice, too, if the Kernel would define tanh and similar methods, anyway.

Thanks so much!

_Copied from original issue: aparapi/aparapi#15_

**Comment by freemo** [comment]
_From @stoerr on October 8, 2015 19:40_

Also, the @OpenCLMapping doesn't seem to have any effect on the generated code. As a workaround, I used

```
@OpenCLMapping(mapTo = "tanh")
protected float tanh(float _f) {
    float epx = exp(_f);
    float enx = exp(-_f);
    return (epx - enx) / (epx + enx);
}
```

and expected this to translate to the OpenCL tanh function, but the whole function is translated to OpenCL as is.

**Comment by freemo** [comment]
_From @grfrost on October 8, 2015 22:26_

Were you adding this to the source of Kernel.java in the aparapi code
tree?  Or your subclass?

**Comment by freemo** [comment]
_From @stoerr on October 9, 2015 9:14_

I was using a subclass. I assume it would have worked if I changed and built aparapi myself.

**Comment by freemo** [comment]
_From @rlamothe on October 26, 2015 6:55_

Is this still an issue with the latest Trunk code?

**Comment by freemo** [comment]
_From @stoerr on October 30, 2015 18:7_

Unfortunately I couln't build it, since there was an error:

C:\R\GitHub\aparapi\com.amd.aparapi\src\java\com\amd\aparapi\device\Device.java:165: error: no suitable method found for hashCode(long)
      return Long.hashCode(getDeviceId());
                 ^
    method Long.hashCode() is not applicable
      (actual and formal argument lists differ in length)
    method Object.hashCode() is not applicable
      (actual and formal argument lists differ in length)

Which seems strange, since there is no Long.hashCode(long) in either JDK7 or 8.

Anyway, is there a nightly build or something to download, which I could try?

**Comment by CoreRasurae** [comment]
@freemo  I couldn't reproduce this issue. Used the following kernel:
```
    public static class TanhKernel extends Kernel {
    	private float out[];
    	
    	public TanhKernel(float[] out) {
    		this.out = out;
    	}

        @OpenCLMapping(mapTo = "tanh")
        protected final float myTanH(float f) {
            return (float)Math.tanh(f);
        }

        @Override
        public void run() {
            float f = 53.0f;
            
            float result = myTanH(f);
            out[0] = f;
            out[1] = result;
        }

        private void test() {
        	execute(1);
        }
    }
```

**Comment by CoreRasurae** [comment]
@freemo I believe this is no longer reproducible because the Math class is already used in the the aparapi Kernel class, thus the class loader for this class as already been cached when it parses the Kernel derived subclasses.

**Comment by freemo** [comment]
@CoreRasurae  Thanks, that could be. We fixed a lot of stuff since this bug was reported. I'll mark it as invalid for now and reopen it if anyone experiences it again in the future.

**Comment by freemo** [comment]
@CoreRasurae  By the way if you want to collect the 25$ bounty on this message me. Its a weird case since it turned out to be fixed earlier but we dont know who actually fixed it (what commit).
