### ISSUE TITLE
Lack of FP64 support produces warning level log, should be info.

### ISSUE THREAD

**Issue by KIC** [Syncleus/aparapi#61]
while JUnit tests run OK, spock tests wont :-(

```
Oct 13, 2017 12:05:41 PM com.aparapi.internal.kernel.KernelRunner fallBackToNextDevice
WARNING: Device failed for ABCCKernel, devices={Intel<GPU>|AMD<GPU>|Intel<CPU>|AMD<CPU>|Java Alternative Algorithm|Java Thread Pool}: FP64 required but not supported
com.aparapi.internal.exception.AparapiException: FP64 required but not supported
	at com.aparapi.internal.kernel.KernelRunner.fallBackToNextDevice(KernelRunner.java:1113)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1311)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1180)

```

**Comment by freemo** [comment]
I'm not sure there is a fix for this in Travis. Looks like Travis hardware
just doesn't support this feature. Does it not run on your local system
either? Does your system have fp64 support?

**Comment by KIC** [comment]
agreed. but the warning also raises when the device is explicitly set to Java Threadpool locally which is quite confusing. Its a debig or in the worst case an info I would suspect.

```kernel.execute(JavaDevice.THREAD_POOL.createRange(time.length))```

**Comment by freemo** [comment]
Ahh yes perhaps the log level should be tweaked a bit for clarity. Let me
look into that and see how easy it might be to change that. Also feel free
to send in your own pull request if you'd like (easy way to get recognition
on the contributors file).

**Comment by freemo** [comment]
@KIC just to update you I've been working with a contributor to get Array creation support. Once thats done ill throw in a tweak to the log level for you.

**Comment by freemo** [comment]
I couldnt find a sane way to change the logger level without effecting other legitimate warnings. Going to recommend this be changed locally in the logger config when needed. Will reopen if anyone has any good suggestions.
