### ISSUE TITLE
Error in KernelProfile, no currentDevice (synchronization error?) -- NullPointerException -- Device null

### ISSUE THREAD

**Issue by carstenhag** [Syncleus/aparapi#74]
Hello, I'm trying to generate some prime numbers and test 2-3 criterias on those. The code is at https://github.com/carstenhag/par49_primes_zeroes_replaced/tree/gpu (gpu branch).

```
Feb 03, 2018 3:52:09 PM com.aparapi.internal.kernel.KernelProfile onEvent
SCHWERWIEGEND: Error in KernelProfile, no currentDevice (synchronization error?
Feb 03, 2018 3:52:09 PM com.aparapi.internal.kernel.KernelProfile onEvent
SCHWERWIEGEND: Error in KernelProfile, no currentDevice (synchronization error?
Exception in thread "main" java.lang.NullPointerException
	at com.aparapi.internal.kernel.KernelProfile.onEvent(KernelProfile.java:90)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1539)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1180)
	at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1170)
	at com.aparapi.Kernel.execute(Kernel.java:2473)
	at com.aparapi.Kernel.execute(Kernel.java:2430)
	at com.aparapi.Kernel.execute(Kernel.java:2405)
	at PrimesWithZeroesReplaced.main(PrimesWithZeroesReplaced.java:116)
```
Debugging into Kernel.class and Range.class, the _device passed into various functions is `null`.

I am totally new to this (so I probably coded something wrong). I had gotten it to execute today in the morning, the program put the gpu under 100% load, but after 2-3 minutes the driver seemed to always crash (the screen went black for some seconds and the program just ended).
Because of this, I wanted to upgrade the Radeon drivers to version 18.2.1. After the update, it's always giving me this error.

This error was also reported on the AMD repo by someone else: https://github.com/aparapi/aparapi/issues/49. He fixed it by "reinstalling" OpenCL. I tried to reinstall the old drivers, the AMD 3.0 SDK, but that didn't change anything. I installed the new drivers again but that didn't help either.

I'm on a Windows 10 x64, R9 290 system. `clinfo` returns the CPU and the GPU as available.

**Comment by carstenhag** [comment]
It happened because of the update to the newest version. The OpenCL version was upgraded.

@freemo The guys at the AMD repo (see the linked issue) say the JNI lib is doing a string comparison on the OpenCL version (at least on their repo), and I have a too new version that is not handled. Because of this, it fails.
I was unable to build their stuff, sadly.

**Comment by freemo** [comment]
Ahh yes that would apply to us as well. In fact we already have a PR for
this.

https://github.com/Syncleus/aparapi-native/pull/6

**Comment by freemo** [comment]
@carstenhag I will have a solution for you to test shortly.

**Comment by freemo** [comment]
@brenzosa and @carstenhag  ok this has been fixed (I hope) and should be released in the next release. I will let you test it on OpenCL 2.1 to confirm everything is in working order, once I get the confirmation that everything appears to work I will make an official release.

Here is the info on what I changed and how to test it.

the Syncleus/aparapi-native project had its code changed (minor) to add OpenCL 2.1 to the list of compatible versions. This is now in the master branch if you want to compile it yourself.

I compiled aparapi-native for windows, linux, and OSX both 32bit and 64 bit. I moved these into the Syncleus/aparapi-jni project under the master branch. This was deployed to our official snapshot repository (publicly available). You can either just download the parapi-jni project and issue "mvn clean install" yourself, or you can rely on the public snapshot repository instead.

At this point you should have aparapi-jni installed which will load aparapi-native files for your os automatically. Now just checkout the aparapi from the master branch and run a `mvn clean install` there and you should be good to go. Let me know if it works.

PS. For now im going to close this ticket, feel free to reopen it if the problem persists. If i dont hear back from anyone in the next few days I'll assume everything is working and proceed with an official release.

**Comment by carstenhag** [comment]
In my `pom.xml` I just changed the `com.aparapi` dependency version to
`<version>1.5.0-SNAPSHOT</version>`
and now it starts. Thanks!

**Comment by freemo** [comment]
@carstenhag excellent. Have you tested on windows?

**Comment by carstenhag** [comment]
Indeed, Windows10x64 with Radeon 18.2.1 and OpenCL 2.1.

**Comment by freemo** [comment]
@carstenhag v1.5.0 of aparapi was just released to maven central. It includes a fix for this.
