### ISSUE TITLE
[Bounty $20] Negative integer in for loop turned into something different

### ISSUE THREAD

**Issue by Vineg** [Syncleus/aparapi#78]
I have a loop `for (int i = -800; i < 800; i++) {`
It compiles into `for (int i = 64736; i<800; i++){`

**Comment by freemo** [comment]
@Vineg can you submit a unit test that reproduces and tests for this bug. If so and we can reproduce it then we have something to write a patch against.

**Comment by freemo** [comment]
@Vineg Also sorry for the delay in responding, I didnt see this issue till just now. Must have slipped through in the email notifications. I usually respond same day.

**Comment by freemo** [comment]
We wont assign this a milestone till we cam reproduce this in a unit test. For now ill remove it from the current release.

**Comment by freemo** [comment]
@Vineg and @CoreRasurae this ticket is now resolved. Fix is in master and will be released in 1.8.0.
