### ISSUE TITLE
[PATCH] Add support for Local arguments in kernel functions

### ISSUE THREAD

**Issue by CoreRasurae** [Syncleus/aparapi#79]
The patches attached enable support for func(@Local int[] arg1, float arg2,...) or func(int[] arg1_$local$, float arg2, ...).

As the following kernel code illustrates:

```
   public class LocalSimpleKernelTest extends Kernel {
 	private static final int LENGTH = 10;
	
	public LocalSimpleKernelTest(final AtomicInteger[] max) {
		myArray = new int[LENGTH];
	}
	
	@Local
	private int myArray[];
		
	public void doIt1(int baseValue, @Local int arr[]) {
		for (int i = 0; i < LENGTH; i++) {
			arr[i] += baseValue;
		}
	}

	public void doIt2(int baseValue, int arr_$local$[]) {
		for (int i = 0; i < LENGTH; i++) {
			arr_$local$[i] *= baseValue;
		}
	}
	
	@Override
	public void run() {
		int base = 10;
		doIt1(base, myArray);
		doIt2(2, myArray);
	}

   }
```
[LocalAnnontationsSupport.patch.txt](https://github.com/Syncleus/aparapi/files/1909686/LocalAnnontationsSupport.patch.txt)

**Comment by freemo** [comment]
@CoreRasurae  Thank you, can you submit this as a pull request, it will help us streamline testing it and getting it into the next release (i should be doing that in the next few days). Thanks for the submission.

**Comment by CoreRasurae** [comment]
@freemo Sure, I can do that, but won't be able to do it today. I am also preparing another patch to add support for increased atomics support by allowing AtomicInteger[] arrays to be mapped as OpenCL integers, thus easily allowing atomic operation both on Java and on OpenCL, in case there is interest for this feature. This would allow all supported OpenCL atomic operations on integers.

**Comment by freemo** [comment]
@CoreRasurae Awesome, yea I'll be happy to add that feature as well as long as there arent any negative impact on existing features (cant imagine there would be). So happy to approve both features, thanks so much.

**Comment by freemo** [comment]
@CoreRasurae merged your PR, Thanks!
