### ISSUE TITLE
Why is globalBarrier() deprecated?

### ISSUE THREAD

**Issue by CoreRasurae** [Syncleus/aparapi#84]
I see that Aparapi has globalBarrier() method - which translates to opencl barrier(CLK_GLOBAL_MEM_FENCE) - deprecated for a long time, but I see no reason to it being deprecated, in fact this makes Aparapi kernels less flexible than opencl actually is, while in this case is trivial not to be.

Also, according to the opencl documentation it is even possible to do:
barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE) to synchronize workgroup threads while also ordering memory accesses on both memories types. To me this would translate to having localGlobalBarrier() in aparapi to not break existing logic while allowing for full functionality on this mater.

One use case for globalBarrier() is when work items in a work group write chunks of data to the global memory and then other work items in the work group need to read those chunks, or part of it.
While localGlobalBarrier() would make sense if both local and global memory spaces were written, while being both read by a different work item in the work group. 

Can globalBarrier() be de-deprecated? Can localGlobalBarrier() be implemented?

According to OpenCL 1.2 documentation:

> All work-items in a work-group executing the
kernel on a processor must execute this function
before any are allowed to continue execution
beyond the barrier. This function must be
encountered by all work-items in a work-group
executing the kernel.

>If barrier is inside a conditional statement, then
all work-items must enter the conditional if any
work-item enters the conditional statement and
executes the barrier.

>If barrier is inside a loop, all work-items must
execute the barrier for each iteration of the loop
before any are allowed to continue execution
beyond the barrier.

>The barrier function also queues a memory fence
(reads and writes) to ensure correct ordering of
memory operations to local or global memory.
The flags argument specifies the memory address
space and can be set to a combination of the
following literal values.

>CLK_LOCAL_MEM_FENCE - The barrier
function will either flush any variables stored in
local memory or queue a memory fence to ensure
correct ordering of memory operations to local
memory.

>CLK_GLOBAL_MEM_FENCE – The barrier
function will queue a memory fence to ensure
correct ordering of memory operations to global
memory. This can be useful when work-items, for
example, write to buffer or image objects and
then want to read the updated data.

**Comment by freemo** [comment]
@CoreRasurae This was deprecated before I took over stewartship of the code. So I dont know the logic behind the deprecation.

@grfrost is the original developer who has been around from the beginning. If anyone knows why it is most likely him.

**Comment by grfrost** [comment]
Some of this may well have been my confusion with the OpenCL 1.1 specs. So it is perfectly reasonable to consider the deprecation status.  I will add a few notes. 

OpenCL was not the only intended target (HSAIL was also considered - actually implemented, but since unsupported), it's memory model was slightly different.

Before changing the workings here, consider what happens to multithreaded Java and even CPU only OpenCL execution.  My guess is that they can all be made to work, but just note that dropping back to JTP mode is expected, and we may need some Java volatile contracts to made ensure that the memory models are cohesive. 

It should not be too hard to plumb these changes through the code.

**Comment by freemo** [comment]
@grfrost thanks so much for the update. Gives us a good starting point for reconsidering this. Also lets do a hang out chat soon to catch up if you're free.

**Comment by CoreRasurae** [comment]
@grfrost  I see... yes, but apart from the HSAIL computation model, I would say that in terms of Java, the problems already exist with the localBarrier(), since memory ordering issues will already exist in JTP. In terms of Java,  localBarrier() or globalBarrier() are the same in terms synchronization, because both refer to the work group synchronization and in terms of memory ordering they're the same too, because the memory is the same. Am I missing something?

**Comment by grfrost** [comment]
No I don't think you are missing something, really just flagging the intent for 'fallback' to Java.  Clearly the Java memory model is less restrictive than the OpenCL one, one can generally ignore it.  I would just suggest some Java side testing once you have an implementation :)

**Comment by CoreRasurae** [comment]
@grfrost  Ok, thanks!

**Comment by CoreRasurae** [comment]
@freemo @grfrost Proposed Javadoc enhacements:

- localBarrier()

>  /**
    * Wait for all kernels in the current group to rendezvous at this call before continuing execution.<br/> 
    * It will also enforce memory ordering, such that modifications made by each thread in the work-group, to the memory,
    * before entering into this barrier call will be visible by all threads leaving the barrier.
    *  
    * **Note1:** In OpenCL will execute as barrier(CLK_LOCAL_MEM_FENCE), which will have a different behavior than in Java,
    * because it will only guarantee visibility of modifications made to **local memory space** to all threads, in the work group, leaving the barrier.
    * **Note2:** In OpenCL it is required that all threads must enter the same if blocks and must iterate
    * the same number of times in all loops (for, while, ...).
    */

- globalBarrier()

> /**
    * Wait for all kernels in the current group to rendezvous at this call before continuing execution.<br/> 
    * It will also enforce memory ordering, such that modifications made by each thread in the work-group, to the memory,
    * before entering into this barrier call will be visible by all threads leaving the barrier.
    *  
    * **Note1:** In OpenCL will execute as barrier(CLK_GLOBAL_MEM_FENCE), which will have a different behavior than in Java,
    * because it will only guarantee visibility of modifications made to **global memory space** to all threads, in the work group, leaving the barrier.
    * **Note2:** In OpenCL it is required that all threads must enter the same if blocks and must iterate
    * the same number of times in all loops (for, while, ...).
    */

- localGlobalBarrier()

> /**
    * Wait for all kernels in the current group to rendezvous at this call before continuing execution.<br/> 
    * It will also enforce memory ordering, such that modifications made by each thread in the work-group, to the memory,
    * before entering into this barrier call will be visible by all threads leaving the barrier.
    * 
    * **Note1:** When in doubt, use this barrier instead of localBarrier() of globalBarrier(), despite the possible
    * performance loss.
    *
    * **Note2:** In OpenCL will execute as barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE), which will have the same behavior as in Java,
    * because it will guarantee the visibility of all modifications made to **any memory space** to all threads, in the work group, leaving the barrier.
    * **Note3:** In OpenCL it is required that all threads must enter the same if blocks and must iterate
    * the same number of times in all loops (for, while, ...).
    */

**Comment by freemo** [comment]
@CoreRasurae Awesome, I think this does a good job at conveying the
caveats. Want to add it in a PR or need me to integrate it manually?

**Comment by CoreRasurae** [comment]
@freemo I am preparaing a PR for this.

**Comment by freemo** [comment]
Commit implementing this has been merged. Closing ticket. Thanks @CoreRasurae  for your contribution.
