### ISSUE TITLE
JtpRangeIdsTest failed due to incorrect expectations.

### ISSUE THREAD

**Issue by freemo** [Syncleus/aparapi#94]
The following test fails and demonstrates the issue: 
https://github.com/Syncleus/aparapi/blob/master/src/test/java/com/aparapi/runtime/JtpRangeIdsTest.java

**Comment by freemo** [comment]
@grfrost Do you know if this test is still accurate and valid?

**Comment by grfrost** [comment]
I do not know here this test came from.  Looks like it is testing the 2D java Range class to ensure that it creates the appropriate dims. But would have to study closer.

**Comment by freemo** [comment]
@grfrost yea im a bit confused myself. Was hoping you might know off hand. No worries, thanks.

**Comment by CoreRasurae** [comment]
@freemo The JtpRangeIdsTest is absolutely **flawed**. I spent some time with this, thinking this was a solvable problem, but it isn't. The test is rigged. For instance consider globalIdX=3, and globalIdY=1, according to the test this would give globalThreadId=1*12+3=15, now if we look into the test table entry test[15] it says that globalIdX should have been 7 and that globalIdY should have been 1, but according to this, that would given test table entry 1*12+7=19... :laughing: 
However still not being happy with this, the current JTP implementation uses a different distribution logic for the threads.

**Comment by CoreRasurae** [comment]
@freemo I do agree that Aparapi could have a better distribution logic, that could mimic better what OpenCL is likely to do, and so executing whole group at a time, instead of executing chunks from different groups at a time, however that would be a new feature, and would have to been done for 2D and 3D ranges. So this test is completely a no go, it only made me loose time to assess bugs in the test itself, while trying to adjust the implementation to follow that OpenCL likely logic.

**Comment by freemo** [comment]
@CoreRasurae So your saying the behavior is normal and the test itself is flawed and should be removed?

**Comment by CoreRasurae** [comment]
@freemo Yes, this test is flawed. However it can be fixed to make some useful validation. It would just test the 2D range, there would be the need for tests for 1D, and 3D ranges.

**Comment by CoreRasurae** [comment]
@freemo removal of the test is an option too. As a test it is useless as it is.

**Comment by freemo** [comment]
@CoreRasurae What are you thought on just adapting the test so the values in the matrix allow it to pass? Since its not a bug that would ensure behavior remains predictable anf garuntees regression.
